/**
 * 中国地区教職員研究大会 ダミー参加者データ 50件 投入スクリプト
 * - 事前申し込み（isWalkin: false）: 43名
 * - 当日申し込み（isWalkin: true）: 7名
 * - 授業公開希望学年: 【A1】第4学年, 【A2】第5学年, 【A3】第6学年
 * - 分科会: 【B1】話すこと・聞くこと, 【B2】書くこと, 【B3】読むこと（文学）, 【B4】読むこと（説明）
 */

const API_BASE_URL = 'https://conference-reception-api.shouichiigi.workers.dev';

const dummyList = [
  // --- 1〜43: 事前申し込み（isWalkin: false） ---
  {
    organization: '鳥取市立久松小学校',
    lastName: '田中',
    firstName: '健一',
    lastNameKana: 'タナカ',
    firstNameKana: 'ケンイチ',
    phone1: '0857',
    phone2: '22',
    phone3: '1101',
    email: 'tanaka.k@tottori-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '駐車場利用希望',
    location: '鳥取県鳥取市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '鳥取大学附属小学校',
    lastName: '佐藤',
    firstName: '美穂',
    lastNameKana: 'サトウ',
    firstNameKana: 'ミホ',
    phone1: '0857',
    phone2: '31',
    phone3: '5010',
    email: 'sato.m@fu.tottori-u.ac.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '午前中のみ参加予定',
    location: '鳥取県鳥取市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '米子市立就将小学校',
    lastName: '山本',
    firstName: '大介',
    lastNameKana: 'ヤマモト',
    firstNameKana: 'ダイスケ',
    phone1: '0859',
    phone2: '33',
    phone3: '4500',
    email: 'yamamoto.d@yonago-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '鳥取県米子市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '倉吉市立成徳小学校',
    lastName: '渡辺',
    firstName: '真由美',
    lastNameKana: 'ワタナベ',
    firstNameKana: 'マユミ',
    phone1: '0858',
    phone2: '22',
    phone3: '3100',
    email: 'watanabe.m@kurayoshi-ed.jp',
    position: '教頭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '鳥取県倉吉市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '境港市立境小学校',
    lastName: '小林',
    firstName: '翔太',
    lastNameKana: 'コバヤシ',
    firstNameKana: 'ショウタ',
    phone1: '0859',
    phone2: '44',
    phone3: '2020',
    email: 'kobayashi.s@sakaiminato-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B2】書くこと',
    notes: 'プロジェクター持参',
    location: '鳥取県境港市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '松江市立乃木小学校',
    lastName: '加藤',
    firstName: '優子',
    lastNameKana: 'カトウ',
    firstNameKana: 'ユウコ',
    phone1: '0852',
    phone2: '24',
    phone3: '8810',
    email: 'kato.y@matsue-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '島根県松江市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '出雲市立今市小学校',
    lastName: '吉田',
    firstName: '拓也',
    lastNameKana: 'ヨシダ',
    firstNameKana: 'タクヤ',
    phone1: '0853',
    phone2: '21',
    phone3: '0055',
    email: 'yoshida.t@izumo-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '島根県出雲市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '浜田市立石見小学校',
    lastName: '松本',
    firstName: '香織',
    lastNameKana: 'マツモト',
    firstNameKana: 'カオリ',
    phone1: '0855',
    phone2: '22',
    phone3: '1432',
    email: 'matsumoto.k@hamada-ed.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '発表者です',
    location: '島根県浜田市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '益田市立益田小学校',
    lastName: '井上',
    firstName: '浩二',
    lastNameKana: 'イノウエ',
    firstNameKana: 'コウジ',
    phone1: '0856',
    phone2: '23',
    phone3: '0870',
    email: 'inoue.k@masuda-ed.jp',
    position: '校長',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '来賓対応あり',
    location: '島根県益田市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '島根県教育庁教育指導課',
    lastName: '木村',
    firstName: '陽子',
    lastNameKana: 'キムラ',
    firstNameKana: 'ヨウコ',
    phone1: '0852',
    phone2: '22',
    phone3: '5420',
    email: 'kimura.y@pref.shimane.lg.jp',
    position: '指導主事',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '視察を兼ねる',
    location: '島根県松江市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '岡山市立岡山中央小学校',
    lastName: '林',
    firstName: '健太',
    lastNameKana: 'ハヤシ',
    firstNameKana: 'ケンタ',
    phone1: '086',
    phone2: '223',
    phone3: '7800',
    email: 'hayashi.k@okayama-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '岡山県岡山市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '倉敷市立倉敷東小学校',
    lastName: '斎藤',
    firstName: '恵子',
    lastNameKana: 'サイトウ',
    firstNameKana: 'ケイコ',
    phone1: '086',
    phone2: '422',
    phone3: '0150',
    email: 'saito.k@kurashiki-ed.jp',
    position: '教頭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '岡山県倉敷市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '津山市立東小学校',
    lastName: '清水',
    firstName: '和也',
    lastNameKana: 'シミズ',
    firstNameKana: 'カズヤ',
    phone1: '0868',
    phone2: '22',
    phone3: '3900',
    email: 'shimizu.k@tsuyama-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '岡山県津山市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '総社市立総社小学校',
    lastName: '山口',
    firstName: '千春',
    lastNameKana: 'ヤマグチ',
    firstNameKana: 'チハル',
    phone1: '0866',
    phone2: '92',
    phone3: '0230',
    email: 'yamaguchi.c@soja-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '岡山県総社市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '岡山県教育委員会事務局',
    lastName: '阿部',
    firstName: '慎吾',
    lastNameKana: 'アベ',
    firstNameKana: 'シンゴ',
    phone1: '086',
    phone2: '226',
    phone3: '7580',
    email: 'abe.s@pref.okayama.lg.jp',
    position: '指導主事',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '指導助言者',
    location: '岡山県岡山市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '広島市立幟町小学校',
    lastName: '池田',
    firstName: '直美',
    lastNameKana: 'イケダ',
    firstNameKana: 'ナオミ',
    phone1: '082',
    phone2: '221',
    phone3: '4500',
    email: 'ikeda.n@hiroshima-city.ed.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '分科会司会',
    location: '広島県広島市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '福山市立霞小学校',
    lastName: '橋本',
    firstName: '竜也',
    lastNameKana: 'ハシモト',
    firstNameKana: 'タツヤ',
    phone1: '084',
    phone2: '923',
    phone3: '1280',
    email: 'hashimoto.t@fukuyama-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '広島県福山市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '呉市立明徳小学校',
    lastName: '山崎',
    firstName: '瞳',
    lastNameKana: 'ヤマザキ',
    firstNameKana: 'ヒトミ',
    phone1: '0823',
    phone2: '21',
    phone3: '8800',
    email: 'yamazaki.h@kure-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '広島県呉市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '東広島市立西条小学校',
    lastName: '森',
    firstName: '貴之',
    lastNameKana: 'モリ',
    firstNameKana: 'タカユキ',
    phone1: '082',
    phone2: '422',
    phone3: '2210',
    email: 'mori.t@higashihiroshima-ed.jp',
    position: '教頭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '広島県東広島市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '広島県教育センター',
    lastName: '石川',
    firstName: '智恵',
    lastNameKana: 'イシカワ',
    firstNameKana: 'チエ',
    phone1: '082',
    phone2: '427',
    phone3: '3000',
    email: 'ishikawa.c@hiroshima-c.ed.jp',
    position: '指導主事',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '指導講評担当',
    location: '広島県東広島市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '山口市立白石小学校',
    lastName: '前田',
    firstName: '俊介',
    lastNameKana: 'マエダ',
    firstNameKana: 'シュンスケ',
    phone1: '083',
    phone2: '922',
    phone3: '0810',
    email: 'maeda.s@yamaguchi-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '山口県山口市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '下関市立名池小学校',
    lastName: '藤田',
    firstName: '由香',
    lastNameKana: 'フジタ',
    firstNameKana: 'ユカ',
    phone1: '083',
    phone2: '222',
    phone3: '4450',
    email: 'fujita.y@shimonoseki-ed.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '山口県下関市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '宇部市立新川小学校',
    lastName: '岡田',
    firstName: '亮太',
    lastNameKana: 'オカダ',
    firstNameKana: 'リョウタ',
    phone1: '0836',
    phone2: '31',
    phone3: '1500',
    email: 'okada.r@ube-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '山口県宇部市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '防府市立佐波小学校',
    lastName: '長谷川',
    firstName: '真理',
    lastNameKana: 'ハセガワ',
    firstNameKana: 'マリ',
    phone1: '0835',
    phone2: '22',
    phone3: '0060',
    email: 'hasegawa.m@hofu-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '',
    location: '山口県防府市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '山口県教育庁学校安全・体育課',
    lastName: '後藤',
    firstName: '誠',
    lastNameKana: 'ゴトウ',
    firstNameKana: 'マコト',
    phone1: '083',
    phone2: '933',
    phone3: '4680',
    email: 'goto.m@pref.yamaguchi.lg.jp',
    position: '指導主事',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '随行員あり',
    location: '山口県山口市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '鳥取市立修立小学校',
    lastName: '近藤',
    firstName: '由美子',
    lastNameKana: 'コンドウ',
    firstNameKana: 'ユミコ',
    phone1: '0857',
    phone2: '23',
    phone3: '3340',
    email: 'kondo.y@tottori-ed.jp',
    position: '教頭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '鳥取県鳥取市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '鳥取県立教育センター',
    lastName: '村上',
    firstName: '勝',
    lastNameKana: 'ムラカミ',
    firstNameKana: 'マサル',
    phone1: '0857',
    phone2: '28',
    phone3: '2321',
    email: 'murakami.m@tottori-c.ed.jp',
    position: '指導主事',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '運営協力員',
    location: '鳥取県鳥取市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '米子市立啓成小学校',
    lastName: '遠藤',
    firstName: '沙織',
    lastNameKana: 'エンドウ',
    firstNameKana: 'サオリ',
    phone1: '0859',
    phone2: '34',
    phone3: '2280',
    email: 'endo.s@yonago-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '鳥取県米子市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '出雲市立大津小学校',
    lastName: '青木',
    firstName: '大輔',
    lastNameKana: 'アオキ',
    firstNameKana: 'ダイスケ',
    phone1: '0853',
    phone2: '22',
    phone3: '3810',
    email: 'aoki.d@izumo-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '島根県出雲市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '広島市立袋町小学校',
    lastName: '坂本',
    firstName: '綾乃',
    lastNameKana: 'サカモト',
    firstNameKana: 'アヤノ',
    phone1: '082',
    phone2: '241',
    phone3: '5030',
    email: 'sakamoto.a@hiroshima-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '広島県広島市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '鳥取市立稲葉山小学校',
    lastName: '西村',
    firstName: '拓也',
    lastNameKana: 'ニシムラ',
    firstNameKana: 'タクヤ',
    phone1: '0857',
    phone2: '23',
    phone3: '1120',
    email: 'nishimura.t@tottori-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '鳥取県鳥取市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '倉吉市立上小鴨小学校',
    lastName: '三浦',
    firstName: '千晶',
    lastNameKana: 'ミウラ',
    firstNameKana: 'チアキ',
    phone1: '0858',
    phone2: '28',
    phone3: '0015',
    email: 'miura.c@kurayoshi-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '鳥取県倉吉市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '米子市立福米西小学校',
    lastName: '藤井',
    firstName: '陽介',
    lastNameKana: 'フジイ',
    firstNameKana: 'ヨウスケ',
    phone1: '0859',
    phone2: '29',
    phone3: '8801',
    email: 'fujii.y@yonago-ed.jp',
    position: '主幹教諭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '鳥取県米子市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '松江市立津田小学校',
    lastName: '岡本',
    firstName: '麻衣',
    lastNameKana: 'オカモト',
    firstNameKana: 'マイ',
    phone1: '0852',
    phone2: '21',
    phone3: '4300',
    email: 'okamoto.m@matsue-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '',
    location: '島根県松江市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '出雲市立塩冶小学校',
    lastName: '中島',
    firstName: '啓太',
    lastNameKana: 'ナカジマ',
    firstNameKana: 'ケイタ',
    phone1: '0853',
    phone2: '21',
    phone3: '1090',
    email: 'nakajima.k@izumo-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '島根県出雲市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '安来市立安来小学校',
    lastName: '原田',
    firstName: '恵',
    lastNameKana: 'ハラダ',
    firstNameKana: 'メグミ',
    phone1: '0854',
    phone2: '22',
    phone3: '2211',
    email: 'harada.m@yasugi-ed.jp',
    position: '教頭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '島根県安来市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '岡山市立津島小学校',
    lastName: '小野',
    firstName: '亮太',
    lastNameKana: 'オノ',
    firstNameKana: 'リョウタ',
    phone1: '086',
    phone2: '252',
    phone3: '0100',
    email: 'ono.r@okayama-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '',
    location: '岡山県岡山市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '倉敷市立万寿小学校',
    lastName: '竹内',
    firstName: '理恵',
    lastNameKana: 'タケウチ',
    firstNameKana: 'リエ',
    phone1: '086',
    phone2: '422',
    phone3: '5520',
    email: 'takeuchi.r@kurashiki-ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '岡山県倉敷市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '玉野市立宇野小学校',
    lastName: '田村',
    firstName: '康平',
    lastNameKana: 'タムラ',
    firstNameKana: 'コウヘイ',
    phone1: '0863',
    phone2: '31',
    phone3: '2100',
    email: 'tamura.k@tamano-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B2】書くこと',
    notes: '',
    location: '岡山県玉野市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '笠岡市立笠岡小学校',
    lastName: '金子',
    firstName: '佳代',
    lastNameKana: 'カネコ',
    firstNameKana: 'カヨ',
    phone1: '0865',
    phone2: '62',
    phone3: '3300',
    email: 'kaneko.k@kasaoka-ed.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '岡山県笠岡市',
    bentoOrdered: true,
    feePaid: false,
    isWalkin: false,
  },
  {
    organization: '広島市立本川小学校',
    lastName: '和田',
    firstName: '健',
    lastNameKana: 'ワダ',
    firstNameKana: 'ケン',
    phone1: '082',
    phone2: '231',
    phone3: '8100',
    email: 'wada.k@hiroshima-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '',
    location: '広島県広島市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '東広島市立寺西小学校',
    lastName: '中山',
    firstName: '由香里',
    lastNameKana: 'ナカヤマ',
    firstNameKana: 'ユカリ',
    phone1: '082',
    phone2: '423',
    phone3: '1000',
    email: 'nakayama.y@higashihiroshima-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '',
    location: '広島県東広島市',
    bentoOrdered: false,
    feePaid: true,
    isWalkin: false,
  },
  {
    organization: '尾道市立久保小学校',
    lastName: '石田',
    firstName: '智也',
    lastNameKana: 'イシダ',
    firstNameKana: 'トモヤ',
    phone1: '0848',
    phone2: '37',
    phone3: '2200',
    email: 'ishida.t@onomichi-ed.jp',
    position: '教頭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '',
    location: '広島県尾道市',
    bentoOrdered: true,
    feePaid: true,
    isWalkin: false,
  },

  // --- 44〜50: 当日申し込み（isWalkin: true） ---
  {
    organization: '三次市立十日市小学校',
    lastName: '上田',
    firstName: '智子',
    lastNameKana: 'ウエダ',
    firstNameKana: 'トモコ',
    phone1: '0824',
    phone2: '62',
    phone3: '3310',
    email: 'ueda.t@miyoshi-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B2】書くこと',
    notes: '当日参加登録',
    location: '広島県三次市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '山口市立大殿小学校',
    lastName: '森田',
    firstName: '俊介',
    lastNameKana: 'モリタ',
    firstNameKana: 'シュンスケ',
    phone1: '083',
    phone2: '922',
    phone3: '0050',
    email: 'morita.s@yamaguchi-city.ed.jp',
    position: '教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B1】話すこと・聞くこと',
    notes: '当日参加登録',
    location: '山口県山口市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '岩国市立岩国小学校',
    lastName: '柴田',
    firstName: '美紀',
    lastNameKana: 'シバタ',
    firstNameKana: 'ミキ',
    phone1: '0827',
    phone2: '41',
    phone3: '0500',
    email: 'shibata.m@iwakuni-ed.jp',
    position: '主幹教諭',
    transportation: '公共交通機関',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B4】読むこと（説明）',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '当日参加登録',
    location: '山口県岩国市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '周南市立徳山小学校',
    lastName: '原',
    firstName: '裕樹',
    lastNameKana: 'ハラ',
    firstNameKana: 'ユウキ',
    phone1: '0834',
    phone2: '21',
    phone3: '0200',
    email: 'hara.y@shunan-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B2】書くこと',
    notes: '当日参加登録',
    location: '山口県周南市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '萩市立明倫小学校',
    lastName: '工藤',
    firstName: '真由',
    lastNameKana: 'クドウ',
    firstNameKana: 'マユ',
    phone1: '0838',
    phone2: '22',
    phone3: '0020',
    email: 'kudo.m@hagi-ed.jp',
    position: '教頭',
    transportation: '自家用車',
    desiredGrade: '【A3】第6学年',
    subcommittee1: '【B3】読むこと（文学）',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '当日参加登録',
    location: '山口県萩市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '鳥取市立美保小学校',
    lastName: '宮崎',
    firstName: '健二',
    lastNameKana: 'ミヤザキ',
    firstNameKana: 'ケンジ',
    phone1: '0857',
    phone2: '22',
    phone3: '8830',
    email: 'miyazaki.k@tottori-ed.jp',
    position: '教諭',
    transportation: '自家用車',
    desiredGrade: '【A1】第4学年',
    subcommittee1: '【B2】書くこと',
    subcommittee2: '【B4】読むこと（説明）',
    notes: '当日参加登録',
    location: '鳥取県鳥取市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
  {
    organization: '鳥取県教育委員会東部教育局',
    lastName: '菅原',
    firstName: '浩美',
    lastNameKana: 'スガワラ',
    firstNameKana: 'ヒロミ',
    phone1: '0857',
    phone2: '22',
    phone3: '5000',
    email: 'sugawara.h@pref.tottori.lg.jp',
    position: '指導主事',
    transportation: '自家用車',
    desiredGrade: '【A2】第5学年',
    subcommittee1: '【B1】話すこと・聞くこと',
    subcommittee2: '【B3】読むこと（文学）',
    notes: '当日参加登録',
    location: '鳥取県鳥取市',
    bentoOrdered: false,
    feePaid: false,
    isWalkin: true,
  },
];

async function seedData() {
  console.log(`[Seed 50] 事前申し込み（43名）＋当日申し込み（7名）の合計50件を登録開始...`);

  let successCount = 0;
  for (let i = 0; i < dummyList.length; i++) {
    const item = dummyList[i];
    try {
      const res = await fetch(`${API_BASE_URL}/api/walkin`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...item,
          checkedIn: false,
          feeConfirmed: false,
          bentoConfirmed: false,
        }),
      });

      if (res.ok) {
        successCount++;
        process.stdout.write(`.`);
      } else {
        const err = await res.json();
        console.error(`\n[Error ${i + 1}]`, err);
      }
    } catch (e) {
      console.error(`\n[Network Error ${i + 1}]`, e.message);
    }
  }

  console.log(`\n[Seed Done] ${successCount} / ${dummyList.length} 件の登録が完了しました！`);
}

seedData();
